name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: DeeshanSharma
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_habits: yes
